name: Build SDK

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '17'
        cache: 'gradle'

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Build SDK and Demo App
      run: ./gradlew build
